"""
Migração gerada pelo Django para criar o modelo Car.

Includes:
    - Car: Modelo representando um carro com atributos como modelo, marca, ano de fábrica, ano do modelo e valor.
"""

# Generated by Django 5.0.7 on 2024-08-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("factory_year", models.IntegerField(blank=True, null=True)),
                ("model_year", models.IntegerField(blank=True, null=True)),
                ("value", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
