"""
Migração gerada pelo Django para adicionar o modelo Brand e alterar o campo brand no modelo Car.

Includes:
    - Brand: Modelo representando uma marca de carro.
    - AlterField: Modifica o campo brand no modelo Car para ser uma ForeignKey relacionada ao modelo Brand.
"""

# Generated by Django 5.0.7 on 2024-08-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_brand",
                to="cars.brand",
            ),
        ),
    ]
