"""
Migração gerada pelo Django para adicionar campos 'photo' e 'plate' ao modelo Car.

Includes:
    - AddField: Adiciona o campo 'photo' (ImageField) ao modelo Car.
    - AddField: Adiciona o campo 'plate' (CharField) ao modelo Car.
"""

# Generated by Django 5.0.7 on 2024-08-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_brand_alter_car_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
