# Generated by Django 5.0.7 on 2024-09-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Define uma classe de migração para o aplicativo 'cars'.

    Esta migração adiciona o campo 'bio' ao modelo 'Car'.
    """

    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
